project:
  type: website

website:
  title: "Evans ePortfolio"
  navbar:
    right:
      - about.qmd
      - Projects.qmd
      - icon: github
        href: https://github.com/MikaEvans11
      - icon: twitter
        href: https://twitter.com/Mikaevans11
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

